"""LayaPolicy implementation and placeholder for Laya learned router backend."""

from typing import Any, Dict, Optional
from .decision import PolicyDecision
from .engine import PolicyEngine
from .rule_policy import RulePolicy


class LayaPolicy(PolicyEngine):
    """Learned policy engine based on Laya (or shadow predictor).

    In shadow mode, Laya makes predictions and logs confidence/probabilities,
    while falling back to the configured fallback policy (default: RulePolicy)
    or preserving the base execution path.
    """

    def __init__(
        self,
        shadow_mode: bool = True,
        fallback_policy: Optional[PolicyEngine] = None,
        model_name_or_path: Optional[str] = None,
    ):
        self.shadow_mode = shadow_mode
        self.fallback_policy = fallback_policy or RulePolicy()
        self.model_name_or_path = model_name_or_path
        self._laya_available = False
        self._init_backend()

    def _init_backend(self) -> None:
        """Check for optional laya package availability."""
        try:
            import laya  # type: ignore # noqa: F401
            self._laya_available = True
        except ImportError:
            self._laya_available = False

    def predict_laya(self, query: str) -> Dict[str, Any]:
        """Obtain raw Laya prediction, probabilities, and confidence."""
        # When laya package or weights are not installed, provide a deterministic placeholder prediction
        query_len = len(query or "")
        is_complex = query_len > 400 or "workflow" in (query or "").lower()

        # Simulated probability distribution for routing classes
        if is_complex:
            probs = {"direct": 0.02, "single_expert": 0.10, "parallel_experts": 0.18, "system2": 0.70}
            pred_class = "system2"
            pred_expert = None
            complexity = "high"
            needs_verify = True
            confidence = 0.70
        else:
            probs = {"direct": 0.05, "single_expert": 0.80, "parallel_experts": 0.10, "system2": 0.05}
            pred_class = "single_expert"
            pred_expert = "technical" if "code" in (query or "").lower() else "general"
            complexity = "low"
            needs_verify = False
            confidence = 0.80

        return {
            "execution_class": pred_class,
            "primary_expert": pred_expert,
            "complexity": complexity,
            "needs_verification": needs_verify,
            "confidence": confidence,
            "probabilities": probs,
            "backend": "laya-native" if self._laya_available else "laya-surrogate",
        }

    def evaluate(
        self,
        query: str,
        context: Optional[Dict[str, Any]] = None,
    ) -> PolicyDecision:
        laya_pred = self.predict_laya(query)

        if self.shadow_mode:
            # Shadow mode: Execute fallback policy, but record Laya prediction in raw_predictions
            base_decision = self.fallback_policy.evaluate(query, context=context)
            # Attach Laya shadow prediction into metadata and raw_predictions
            base_decision.raw_predictions["laya_shadow"] = laya_pred
            base_decision.metadata["laya_shadow"] = laya_pred
            return base_decision

        # Active mode: Use Laya's prediction directly
        return PolicyDecision(
            execution_class=laya_pred["execution_class"],
            primary_expert=laya_pred.get("primary_expert"),
            model_tier="strong" if laya_pred["execution_class"] == "system2" else "fast",
            needs_verification=laya_pred.get("needs_verification", False),
            max_agent_calls=5 if laya_pred["execution_class"] == "system2" else 1,
            confidence=laya_pred.get("confidence", 0.8),
            raw_predictions={"laya": laya_pred},
            reasoning=f"Decision generated by LayaPolicy ({laya_pred['backend']}).",
        )

    async def aevaluate(
        self,
        query: str,
        context: Optional[Dict[str, Any]] = None,
    ) -> PolicyDecision:
        return self.evaluate(query, context=context)
